add_vehicle:
  target: {}
  fields:
    name:
      required: true
      selector:
        text:

    make:
      required: true
      selector:
        text:

    model:
      required: true
      selector:
        text:

    year:
      required: true
      selector:
        number:
          min: 1900
          max: 2100
          mode: box

    vehicle_type:
      required: true
      selector:
        text:

    vin:
      required: false
      selector:
        text:

set_mileage:
  target: {}
  fields:
    vehicle_id:
      required: true
      selector: 
        text:

    mileage:
      required: true
      selector:
        number:

add_maintenance_item:
  target: {}
  fields:
    vehicle_id:
      required: true
      selector:
        text:

    name:
      required: true
      selector:
        text:

    interval_distance:
      required: false
      selector:
        number:
          min: 1
          mode: box

    interval_hours:
      required: false
      selector:
        number:
          min: 1
          mode: box

add_service_record:
  target: {}
  fields:
    vehicle_id:
      required: true
      selector:
        text:
    
    date:
      required: true
      selector:
        date:
    
    mileage:
      required: true
      selector:
        number:
          min: 0
          mode: box
